### ISSUE TITLE
docstring in project

### ISSUE THREAD

**Issue by gajoc** [dockerlamp/mono-stack#6]
Use JsDoc (http://usejsdoc.org/) or similar

**Comment by yaneek** [comment]
Its not enhancment (no new features), its good practice like unit test writing, just write jsdocs when needed.  We dont have any tasks for "write test" because its not separate job.

**Comment by gajoc** [comment]
conclusion: write comments when needed (for bussiness logic explanation mostly), docs for classes/function etc. not needed now (function and param names should be self explanatory and legible).
